# Generated by Django 5.0.6 on 2024-07-02 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Room Name')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('floor', models.IntegerField(choices=[(1, '1st Floor'), (2, '2nd Floor'), (3, '3rd Floor')], verbose_name='Floor')),
                ('facility', models.TextField(blank=True, null=True, verbose_name='Facilities')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Booking Time')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('usage', models.CharField(choices=[('i', 'Internal'), ('e', 'External')], max_length=1, verbose_name='Usage')),
                ('request', models.TextField(blank=True, null=True, verbose_name='Special Requests')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_app.room', verbose_name='Room')),
            ],
        ),
    ]
