# Generated by Django 5.0.6 on 2024-07-02 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_remove_booking_duration_remove_booking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 12, 32, 58, 596143, tzinfo=datetime.timezone.utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 11, 32, 58, 596143, tzinfo=datetime.timezone.utc), verbose_name='Start Time'),
        ),
    ]
