# Generated by Django 5.0.6 on 2024-07-02 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 11, 36, 1, 371568, tzinfo=datetime.timezone.utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 10, 36, 1, 371568, tzinfo=datetime.timezone.utc), verbose_name='Start Time'),
        ),
    ]
