# Generated by Django 5.0.6 on 2024-07-03 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(1, 'USED'), (0, 'AVAILABLE')], default=0, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 5, 56, 36, 81278, tzinfo=datetime.timezone.utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 4, 56, 36, 81278, tzinfo=datetime.timezone.utc), verbose_name='Start Time'),
        ),
    ]
