# Generated by Django 5.0.6 on 2024-07-04 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_room_status_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 4, 12, 5, 431179, tzinfo=datetime.timezone.utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 3, 12, 5, 431179, tzinfo=datetime.timezone.utc), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unavailable'), (0, 'Available')], verbose_name='Status'),
        ),
    ]
